---
- name: check db Data directory is not empty
  find:
    paths: '/var/lib/pgsql/9.6/data'
  register: filesFound

- name: Database Initialization
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: filesFound.matched == 0

- debug:
    msg: 'Data directory is not empty!'
  when: filesFound.matched > 0
