---
- name: Remove old version of Postgresql
  yum:
    name: postgresql-*
    state: absent

- name: Install EPEL repository
  yum: 
    name: 'epel-release'
    state: present

- name: Add the postgresql repository to your machine by installing PostgreSQL repo rpm 
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm       
    state: present

  
- name: Install PostgreSQL v9.6
  package: 
    name: ['python-pip', 'postgresql96-server', 'postgresql96', 'python-psycopg2']
    state: present
    update_cache: yes

- name: Install psycopg2 for ansible to be able to create postgresql users
  pip: 
    name: psycopg2-binary